
name: github action demo pipeline

on:
  push:
    branches:
      - main

jobs:
  extract-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show Python version
        run: python --version
      - name: Install dependencies
        run: pip install pandas
      - name: Run python program
        run: python extract.py

      